### ISSUE TITLE
"Search for Sam Walton Book" fails with Command 'resizeWindow' is not allowed or doesn't exist

### ISSUE THREAD

**Issue by Stuk** [TestArmada/boilerplate-nightwatch#1]
Ran the suggested command, `./node_modules/.bin/magellan --serial --browser=chrome`

node --version: v0.12.7
npm --version: 2.11.3

```
[Walmart Book] Test Suite
=========================

Running:  Search for Sam Walton Book
Error: Command 'resizeWindow' is not allowed or doesn't exist
    at /Users/xxx/testarmada/boilerplate/node_modules/testarmada-magellan-nightwatch/lib/client-api.js:45:13
    at null.<anonymous> (/Users/xxx/testarmada/boilerplate/node_modules/testarmada-magellan-nightwatch/node_modules/methodmissing/lib/methodmissing.js:26:18)
    at Object.module.exports.Test.Search for Sam Walton Book (/Users/xxx/testarmada/boilerplate/tests/walmart-book.js:7:8)
    at Object.steps.(anonymous function) (/Users/xxx/testarmada/boilerplate/node_modules/testarmada-magellan-nightwatch/lib/client-api.js:82:22)
    at Module.call (/Users/xxx/testarmada/boilerplate/node_modules/nightwatch/lib/runner/module.js:59:34)
    at /Users/xxx/testarmada/boilerplate/node_modules/nightwatch/lib/runner/testcase.js:79:29
    at _fulfilled (/Users/xxx/testarmada/boilerplate/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/xxx/testarmada/boilerplate/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/xxx/testarmada/boilerplate/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /Users/xxx/testarmada/boilerplate/node_modules/nightwatch/node_modules/q/q.js:556:49
```

**Comment by asunar** [comment]
+1
![resize](https://cloud.githubusercontent.com/assets/204049/8861073/a9329196-314d-11e5-800d-b0f2717642fd.png)

![suite](https://cloud.githubusercontent.com/assets/204049/8861115/f2f19eda-314d-11e5-9fdf-5ee73b223dd0.png)

**Comment by asunar** [comment]
resizeWindow is not in the whitelist. To resolve this error change 
boilerplate\node_modules\testarmada-magellan-nightwatch\lib\whitelist.js file like this

  nightwatchCommandWhitelist = [
  "clearValue",
  "pause",
  "setCookie",
  "waitForElementNotPresent",
  "url",
  "saveScreenshot",
  "resizeWindow"
],

**Comment by geekdave** [comment]
Ack - should not have been closed until `package.json` was updated.

**Comment by geekdave** [comment]
Ok, `package.json` updated in https://github.com/TestArmada/boilerplate/commit/9d42d3c48726e2a9adb00746696d666d041f43cb - Closing - fixed.

**Comment by geekdave** [comment]
@Stuk @asunar : _MAJOR_ apologies about this.  Total release failure on my part.  TBH, I had been lazy and was editing a dependency project's files directly in the `node_modules` hierarchy, without using `npm link`.  So my local file system had a working build, but the remote copy did not. 

I've logged https://github.com/TestArmada/boilerplate/issues/2 for us to migrate our internal CI to TravisCI so we can catch stupid mistakes like this.
