### ISSUE TITLE
followed the steps on http://testarmada.github.io/ and got this errors

### ISSUE THREAD

**Issue by jpita** [TestArmada/boilerplate-nightwatch#33]
```| ~/testArmada/boilerplate @ Joses-macbook (josepita)
| => ./node_modules/.bin/magellan --serial --browser=chrome
Magellan 8.8.4
Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/josepita/testArmada/boilerplate/magellan.json
Magellan is creating temporary files at: /Users/josepita/testArmada/boilerplate/temp
Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json
Scanning tests for test files ...
Found 2 test files in tests

Running 2 tests in serial mode with chrome

--> Serial mode, mock port:12000, running test: tests/demo-first.js @chrome
Starting selenium server... started - PID:  51588
nightwatch-magellan has found nightwatch configuration at  /Users/josepita/testArmada/boilerplate/temp/build-magellan-644ef5c3ae1bc_1a28b874af4b7d__temp_assets/nightwatch.json

[Demo First] Test Suite
=======================
starting drydock 0.4.4 server on 127.0.0.1:12000...

Running:  Load demo page
No assertions ran.

Running:  Verify all cities
 ✔ Testing if selector <#tokyo> contains text <Tokyo> after 250 milliseconds
 ✔ Testing if selector <.city:eq(1) p:eq(1)> contains text <Europe> after 226 milliseconds

OK. 2 assertions passed. (482ms)
stopping server...

OK. 2 total assertions passed. (7.46s)

(1 / 2) PASS  tests/demo-first.js @chrome

--> Serial mode, mock port:12003, running test: tests/demo-page-object.js @chrome
Starting selenium server... started - PID:  51601
nightwatch-magellan has found nightwatch configuration at  /Users/josepita/testArmada/boilerplate/temp/build-magellan-644ef5c3ae1bc_4d23ddaf4ccc0__temp_assets/nightwatch.json
[ERR]: data file load failed Error: Cannot find module '/Users/josepita/testArmada/boilerplate/conf/data/default.js'
[ERR]: no data will be loaded

[Demo Page Object] Test Suite
=============================
starting drydock 0.4.4 server on 127.0.0.1:12003...

Running:  Load demo first page
No assertions ran.

Running:  Verify all cities on first page
 ✔ Testing if selector <#tokyo> contains text <Tokyo> after 244 milliseconds
 ✔ Testing if selector <.city:eq(1) p:eq(1)> contains text <Europe> after 228 milliseconds

OK. 2 assertions passed. (487ms)

Running:  Jump to demo second page
 ✔ Selector 'Section[name=jumptoseconddemo],Element[name=@link]' was visible after 247 milliseconds.
 ✔ Selector <Section[name=jumptoseconddemo],Element[name=@link]> clicked after 312 milliseconds

OK. 2 assertions passed. (580ms)

Running:  Verify cities on second page
 ✔ Selector 'Section[name=beijing],Element[name=@title]' was visible after 249 milliseconds.
 ✔ Testing if selector <#beijing> contains text <Beijing> after 222 milliseconds
 ✔ Testing if selector <Section[name=beijing],Element[name=@description]> contains text <China> after 227 milliseconds
 ✔ Testing if selector <Section[name=beijing],Element[name=@content]> contains text <It is the most populous city in the China> after 230 milliseconds

OK. 4 assertions passed. (944ms)

Running:  Verify cities on second page - performance improvement
 ✔ Selector '#beijing' was visible after 220 milliseconds.
 ✔ Testing if selector <#beijing> contains text <Beijing> after 221 milliseconds
 ✔ Testing if selector <#description> contains text <China> after 219 milliseconds
 ✔ Testing if selector <#content> contains text <It is the most populous city in the China> after 220 milliseconds

OK. 4 assertions passed. (891ms)

Running:  Verify cities on second page - maintenance improvement
✖ TypeError: Cannot read property 'title' of undefined
    at Object.module.exports.Test.Verify cities on second page - maintenance improvement (/Users/josepita/testArmada/boilerplate/tests/demo-page-object.js:61:21)
    at Object.steps.(anonymous function) (/Users/josepita/testArmada/boilerplate/node_modules/testarmada-nightwatch-extra/lib/selenium-session-acquisition-wrapper.js:35:22)
    at Module.call (/Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:796:13)
    at /Users/josepita/testArmada/boilerplate/node_modules/q/q.js:556:49
    at runSingle (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:137:13)
    at flush (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

FAILED:  1 assertions failed (7ms)
stopping server...

----------------------------------------------------
TEST FAILURE: 1 assertions failed, 12 passed (9.844s)
 ✖ demo-page-object
   - Verify cities on second page - maintenance improvement


(2 / 2) FAIL (will retry).  Spent 10447 msec tests/demo-page-object.js @chrome

--> Serial mode, mock port:12006, running test: tests/demo-page-object.js @chrome
Starting selenium server... started - PID:  51617
nightwatch-magellan has found nightwatch configuration at  /Users/josepita/testArmada/boilerplate/temp/build-magellan-644ef5c3ae1bc_13f5a11f61a42a__temp_assets/nightwatch.json
[ERR]: data file load failed Error: Cannot find module '/Users/josepita/testArmada/boilerplate/conf/data/default.js'
[ERR]: no data will be loaded

[Demo Page Object] Test Suite
=============================
starting drydock 0.4.4 server on 127.0.0.1:12006...

Running:  Load demo first page
No assertions ran.

Running:  Verify all cities on first page
 ✔ Testing if selector <#tokyo> contains text <Tokyo> after 246 milliseconds
 ✔ Testing if selector <.city:eq(1) p:eq(1)> contains text <Europe> after 240 milliseconds

OK. 2 assertions passed. (499ms)

Running:  Jump to demo second page
 ✔ Selector 'Section[name=jumptoseconddemo],Element[name=@link]' was visible after 253 milliseconds.
 ✔ Selector <Section[name=jumptoseconddemo],Element[name=@link]> clicked after 320 milliseconds

OK. 2 assertions passed. (594ms)

Running:  Verify cities on second page
 ✔ Selector 'Section[name=beijing],Element[name=@title]' was visible after 246 milliseconds.
 ✔ Testing if selector <#beijing> contains text <Beijing> after 221 milliseconds
 ✔ Testing if selector <Section[name=beijing],Element[name=@description]> contains text <China> after 229 milliseconds
 ✔ Testing if selector <Section[name=beijing],Element[name=@content]> contains text <It is the most populous city in the China> after 227 milliseconds

OK. 4 assertions passed. (935ms)

Running:  Verify cities on second page - performance improvement
 ✔ Selector '#beijing' was visible after 221 milliseconds.
 ✔ Testing if selector <#beijing> contains text <Beijing> after 221 milliseconds
 ✔ Testing if selector <#description> contains text <China> after 220 milliseconds
 ✔ Testing if selector <#content> contains text <It is the most populous city in the China> after 219 milliseconds

OK. 4 assertions passed. (894ms)

Running:  Verify cities on second page - maintenance improvement
✖ TypeError: Cannot read property 'title' of undefined
    at Object.module.exports.Test.Verify cities on second page - maintenance improvement (/Users/josepita/testArmada/boilerplate/tests/demo-page-object.js:61:21)
    at Object.steps.(anonymous function) (/Users/josepita/testArmada/boilerplate/node_modules/testarmada-nightwatch-extra/lib/selenium-session-acquisition-wrapper.js:35:22)
    at Module.call (/Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:796:13)
    at /Users/josepita/testArmada/boilerplate/node_modules/q/q.js:556:49
    at runSingle (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:137:13)
    at flush (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

FAILED:  1 assertions failed (8ms)
stopping server...

----------------------------------------------------
TEST FAILURE: 1 assertions failed, 12 passed (9.979s)
 ✖ demo-page-object
   - Verify cities on second page - maintenance improvement


(2 / 2) FAIL (will retry).  Spent 10605 msec tests/demo-page-object.js @chrome

--> Serial mode, mock port:12009, running test: tests/demo-page-object.js @chrome
Starting selenium server... started - PID:  51631
nightwatch-magellan has found nightwatch configuration at  /Users/josepita/testArmada/boilerplate/temp/build-magellan-644ef5c3ae1bc_a4669d07966b8__temp_assets/nightwatch.json
[ERR]: data file load failed Error: Cannot find module '/Users/josepita/testArmada/boilerplate/conf/data/default.js'
[ERR]: no data will be loaded

[Demo Page Object] Test Suite
=============================
starting drydock 0.4.4 server on 127.0.0.1:12009...

Running:  Load demo first page
No assertions ran.

Running:  Verify all cities on first page
 ✔ Testing if selector <#tokyo> contains text <Tokyo> after 248 milliseconds
 ✔ Testing if selector <.city:eq(1) p:eq(1)> contains text <Europe> after 226 milliseconds

OK. 2 assertions passed. (486ms)

Running:  Jump to demo second page
 ✔ Selector 'Section[name=jumptoseconddemo],Element[name=@link]' was visible after 252 milliseconds.
 ✔ Selector <Section[name=jumptoseconddemo],Element[name=@link]> clicked after 317 milliseconds

OK. 2 assertions passed. (589ms)

Running:  Verify cities on second page
 ✔ Selector 'Section[name=beijing],Element[name=@title]' was visible after 248 milliseconds.
 ✔ Testing if selector <#beijing> contains text <Beijing> after 221 milliseconds
 ✔ Testing if selector <Section[name=beijing],Element[name=@description]> contains text <China> after 229 milliseconds
 ✔ Testing if selector <Section[name=beijing],Element[name=@content]> contains text <It is the most populous city in the China> after 227 milliseconds

OK. 4 assertions passed. (940ms)

Running:  Verify cities on second page - performance improvement
 ✔ Selector '#beijing' was visible after 220 milliseconds.
 ✔ Testing if selector <#beijing> contains text <Beijing> after 222 milliseconds
 ✔ Testing if selector <#description> contains text <China> after 221 milliseconds
 ✔ Testing if selector <#content> contains text <It is the most populous city in the China> after 219 milliseconds

OK. 4 assertions passed. (892ms)

Running:  Verify cities on second page - maintenance improvement
✖ TypeError: Cannot read property 'title' of undefined
    at Object.module.exports.Test.Verify cities on second page - maintenance improvement (/Users/josepita/testArmada/boilerplate/tests/demo-page-object.js:61:21)
    at Object.steps.(anonymous function) (/Users/josepita/testArmada/boilerplate/node_modules/testarmada-nightwatch-extra/lib/selenium-session-acquisition-wrapper.js:35:22)
    at Module.call (/Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:796:13)
    at /Users/josepita/testArmada/boilerplate/node_modules/q/q.js:556:49
    at runSingle (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:137:13)
    at flush (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

FAILED:  1 assertions failed (7ms)
stopping server...

----------------------------------------------------
TEST FAILURE: 1 assertions failed, 12 passed (9.865s)
 ✖ demo-page-object
   - Verify cities on second page - maintenance improvement


(2 / 2) FAIL  tests/demo-page-object.js @chrome


============= Failed Tests:  =============


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Failed Test: tests/demo-page-object.js @chrome
 # attempts: 3
     output:
13:24:39 Magellan child process start

13:24:39 Starting selenium server...
13:24:40 started - PID:  51631
13:24:40 nightwatch-magellan has found nightwatch configuration at  /Users/josepita/testArmada/boilerplate/temp/build-magellan-644ef5c3ae1bc_a4669d07966b8__temp_assets/nightwatch.json
13:24:40 [ERR]: data file load failed Error: Cannot find module '/Users/josepita/testArmada/boilerplate/conf/data/default.js'
13:24:40 [ERR]: no data will be loaded
13:24:40 [Demo Page Object] Test Suite
13:24:40 =============================
13:24:40 starting drydock 0.4.4 server on 127.0.0.1:12009...
13:24:40 Running:  Load demo first page
13:24:41 No assertions ran.
13:24:41 Running:  Verify all cities on first page
13:24:42  ✔ Testing if selector <#tokyo> contains text <Tokyo> after 248 milliseconds
13:24:42  ✔ Testing if selector <.city:eq(1) p:eq(1)> contains text <Europe> after 226 milliseconds
13:24:42 OK. 2 assertions passed. (486ms)
13:24:42 Running:  Jump to demo second page
13:24:42  ✔ Selector 'Section[name=jumptoseconddemo],Element[name=@link]' was visible after 252 milliseconds.
13:24:43  ✔ Selector <Section[name=jumptoseconddemo],Element[name=@link]> clicked after 317 milliseconds
13:24:43 OK. 2 assertions passed. (589ms)
13:24:43 Running:  Verify cities on second page
13:24:43  ✔ Selector 'Section[name=beijing],Element[name=@title]' was visible after 248 milliseconds.
13:24:43  ✔ Testing if selector <#beijing> contains text <Beijing> after 221 milliseconds
13:24:43  ✔ Testing if selector <Section[name=beijing],Element[name=@description]> contains text <China> after 229 milliseconds
13:24:44  ✔ Testing if selector <Section[name=beijing],Element[name=@content]> contains text <It is the most populous city in the China> after 227 milliseconds
13:24:44 OK. 4 assertions passed. (940ms)
13:24:44 Running:  Verify cities on second page - performance improvement
13:24:44  ✔ Selector '#beijing' was visible after 220 milliseconds.
13:24:44  ✔ Testing if selector <#beijing> contains text <Beijing> after 222 milliseconds
13:24:44  ✔ Testing if selector <#description> contains text <China> after 221 milliseconds
13:24:44  ✔ Testing if selector <#content> contains text <It is the most populous city in the China> after 219 milliseconds
13:24:44 OK. 4 assertions passed. (892ms)
13:24:44 Running:  Verify cities on second page - maintenance improvement
13:24:44 ✖ TypeError: Cannot read property 'title' of undefined
13:24:44     at Object.module.exports.Test.Verify cities on second page - maintenance improvement (/Users/josepita/testArmada/boilerplate/tests/demo-page-object.js:61:21)
13:24:44     at Object.steps.(anonymous function) (/Users/josepita/testArmada/boilerplate/node_modules/testarmada-nightwatch-extra/lib/selenium-session-acquisition-wrapper.js:35:22)
13:24:44     at Module.call (/Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/module.js:63:34)
13:24:44     at /Users/josepita/testArmada/boilerplate/node_modules/nightwatch/lib/runner/testcase.js:97:29
13:24:44     at _fulfilled (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:834:54)
13:24:44     at self.promiseDispatch.done (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:863:30)
13:24:44     at Promise.promise.promiseDispatch (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:796:13)
13:24:44     at /Users/josepita/testArmada/boilerplate/node_modules/q/q.js:556:49
13:24:44     at runSingle (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:137:13)
13:24:44     at flush (/Users/josepita/testArmada/boilerplate/node_modules/q/q.js:125:13)
13:24:44     at _combinedTickCallback (internal/process/next_tick.js:67:7)
13:24:44     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
13:24:44 FAILED:  1 assertions failed (7ms)
13:24:44 stopping server...
13:24:49 ----------------------------------------------------
13:24:49 TEST FAILURE: 1 assertions failed, 12 passed (9.865s)
13:24:49  ✖ demo-page-object
13:24:49    - Verify cities on second page - maintenance improvement



============= Suite Complete =============

     Status: FAILED
    Runtime: 50.4s
Total tests: 2
 Successful: 1 / 2
     Failed: 1 / 2```

**Comment by archlichking** [comment]
You'll have to add `DPRO=local` to your command. The full command is
```
DPRO=local ./node_modules/.bin/magellan --serial --browser chrome
```
