### ISSUE TITLE
latest code gives following error

### ISSUE THREAD

**Issue by amitmawkin** [TestArmada/boilerplate-nightwatch#50]
```
> testarmada-boilerplate-nightwatch@3.0.0 test /Users/XXXXXX/dev/boilerplate-nightwatch
> DPRO=local ./node_modules/.bin/magellan --local_browsers chrome,firefox

[INFO] [Magellan] Magellan is creating temporary files at: /Users/XXXXX/dev/boilerplate-nightwatch/temp
[INFO] [Magellan] Magellan 10.0.1
[INFO] [Magellan] Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/XXXXX/dev/boilerplate-nightwatch/magellan.json
[INFO] [Magellan] Loaded test framework:
[INFO] [Magellan]   testarmada-magellan-nightwatch-plugin
[INFO] [Magellan] Loaded test executors:
[INFO] [Magellan]   testarmada-magellan-local-executor
[INFO] [Magellan]   testarmada-magellan-sauce-executor
[INFO] [Magellan]   testarmada-magellan-browserstack-executor
[INFO] [Magellan Nightwatch Plugin] test iterator found nightwatch configuration at: ./conf/nightwatch.json
[INFO] [Magellan Nightwatch Plugin] Scanning tests for test files ...
[INFO] [Magellan Nightwatch Plugin] Found 2 test files in tests
[ERROR] [Magellan] Error initializing Magellan
[ERROR] [Magellan] Error description:
[ERROR] [Magellan] Error: no auth mechanism defined
[ERROR] [Magellan] Error stack trace:
[ERROR] [Magellan] Error: no auth mechanism defined
    at Auth.onRequest (/Users/XXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/node_modules/request/lib/auth.js:133:32)
    at Request.auth (/Users/XXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/node_modules/request/request.js:1360:14)
    at Request.init (/Users/XXXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/node_modules/request/request.js:378:10)
    at new Request (/Users/XXXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/node_modules/request/request.js:130:8)
    at request (/Users/XXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/node_modules/request/index.js:54:10)
    at Function.get (/Users/XXXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/node_modules/request/index.js:62:12)
    at /Users/XXXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/lib/pancake.js:65:27
    at Object.initialize (/Users/XXXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/lib/pancake.js:48:12)
    at Object.getProfiles (/Users/XXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/lib/profile.js:51:30)
    at _.forEach (/Users/XXXXX/dev/boilerplate-nightwatch/node_modules/testarmada-magellan/src/profiles.js:143:48)
npm ERR! Test failed.  See above for more details.
```

**Comment by archlichking** [comment]
@amitmawkin this comes from `testarmada-magellan-browserstack-executor`, which is in `magellan.json`. the error is because of the absence of env variables required by browserstack executor [link](https://github.com/TestArmada/magellan-browserstack-executor#how-to-use).

you can remove `testarmada-magellan-browserstack-executor` from `magellan.json` if you dont use it, or follow the link to set env variables up.

**Comment by amitmawkin** [comment]
thanks.. that fixes the auth issue.
