### ISSUE TITLE
`npm run test` fails

### ISSUE THREAD

**Issue by bartlomn** [TestArmada/boilerplate-nightwatch#53]
### Given script:
```
git clone git@github.com:TestArmada/boilerplate-nightwatch.git
cd boilerplate-nightwatch
npm install
npm run test
```

### Expected:
tests are executed

### Actual:
```
[INFO] [Magellan Nightwatch Plugin] Found 2 test files in tests
[ERROR] [Magellan] Error initializing Magellan
[ERROR] [Magellan] Error description:
[ERROR] [Magellan] Error: no auth mechanism defined
[ERROR] [Magellan] Error stack trace:
[ERROR] [Magellan] Error: no auth mechanism defined
    at Auth.onRequest (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/request/lib/auth.js:133:32)
    at Request.auth (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/request/request.js:1360:14)
    at Request.init (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/request/request.js:378:10)
    at new Request (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/request/request.js:130:8)
    at request (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/request/index.js:54:10)
    at Function.get (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/request/index.js:62:12)
    at /Users/bartn/Desktop/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/lib/pancake.js:65:27
    at Object.initialize (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/lib/pancake.js:48:12)
    at Object.getProfiles (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/testarmada-magellan-browserstack-executor/lib/profile.js:51:30)
    at _.forEach (/Users/bartn/Desktop/boilerplate-nightwatch/node_modules/testarmada-magellan/src/profiles.js:143:48)
```

Tested under `OSX 10.12.3`, node versions ` v4.8.1`, `v5.12.0` and `v6.10.1`

I assume it's dependency related. Please advise.

**Comment by archlichking** [comment]
@bartlomn remove these two lines
> https://github.com/TestArmada/boilerplate-nightwatch/blob/master/magellan.json#L5-L6

otherwise you'll have to follow the steps in executors readme to setup env vars for both executors.
> https://github.com/TestArmada/magellan-browserstack-executor#how-to-use
> https://github.com/TestArmada/magellan-saucelabs-executor#how-to-use
