### ISSUE TITLE
Connecting to Drydock fails on Mac

### ISSUE THREAD

**Issue by testAccount4325** [TestArmada/boilerplate-nightwatch#57]
Demo Web] Test Suite
=========================
starting drydock 0.4.4 server on travis.dev:12001...
(node:7641) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Error writing log file to: /Users/me/TestArmada/boilerplate-nightwatch/reports/selenium-debug.log
[INFO] [Nightwatch Extra] No appium is configured in nightwatch.json, skip appium stop

There was an error while starting the test runner:

Error: listen EADDRNOTAVAIL 127.0.53.53:12001
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1247:19)
    at listenInCluster (net.js:1304:12)
    at doListen (net.js:1428:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)

[INFO] [Magellan] (1 / 1) FAIL (will retry).  Spent 1101 msec tests/demo-web.js @env:chrome|executor:local

**Comment by testAccount4325** [comment]
deleting the host|| part from drydock seems to have made this work.

**Comment by archlichking** [comment]
please see comment in #58
