### ISSUE TITLE
fresh install and run errors

### ISSUE THREAD

**Issue by viktor-equinix** [TestArmada/boilerplate-nightwatch#70]
Created a clone of repo as suggested on http://testarmada.io/
> git clone git@github.com:TestArmada/boilerplate-nightwatch.git

on run `npm install` got this error:
```
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
events.js:183░░░░░░⸩ ⠹ extract:mv: sill extract glob@7.1.2
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/user/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
```

then on run `npm run test:desktop` or `DPRO=local ./node_modules/.bin/magellan --local_browser chrome --test tests/demo-simple.js --serial` - the same error
```
[INFO] [Nightwatch Extra] [Appium Plugin] No appium is configured in nightwatch.json, skip appium start
[INFO] [Nightwatch Extra] [Error Dictionary Plugin] Found dictionary at ./nightwatch_dictionary.js, loading dictionary
starting drydock 0.4.4 server on dev.walmart.com:12001...
(node:48630) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
{ Error: getaddrinfo ENOTFOUND dev.walmart.com
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'dev.walmart.com' }
[INFO] [Magellan] (1 / 1) PASS  tests/demo-web.js @env:chrome|executor:local
[INFO] [Magellan] ============= Suite Complete =============
[INFO] [Magellan]      Status: PASSED
[INFO] [Magellan]     Runtime: 5.3s
[INFO] [Magellan] Total tests: 1
[INFO] [Magellan]  Successful: 1 / 1
```

```
node -v
v8.11.1

npm -v
5.8.0

MacOS v10.13.4
```

If some configuration was missed in tutorial which can prevent such error, can you suggest what else need to modify/update?

Thanks

**Comment by viktor-equinix** [comment]
Looks like 1st issue above happened due missing java SDK (fresh system), so after installing java and running `npm install` again such error is not showing anymore, but 2nd error above still persist.
